branches:
  only:
  - master

language: cpp
env: CXX=g++-7

install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install libxrandr-dev libxinerama-dev libxcursor-dev libx11-dev libxi-dev gcc-7 g++-7 mesa-common-dev
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7

script: cmake . && make -j2
