# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.13.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.13.4/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/julyzamora/Desktop/Game/game

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/julyzamora/Desktop/Game/game

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.13.4/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.13.4/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.13.4/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.13.4/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.13.4/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.13.4/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.13.4/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.13.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"assimp-dev\" \"libassimp4.1.0\" \"libassimp4.1.0-dev\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/julyzamora/Desktop/Game/game/CMakeFiles /Users/julyzamora/Desktop/Game/game/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/julyzamora/Desktop/Game/game/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Game-Server

# Build rule for target.
Game-Server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Game-Server
.PHONY : Game-Server

# fast build rule for target.
Game-Server/fast:
	$(MAKE) -f CMakeFiles/Game-Server.dir/build.make CMakeFiles/Game-Server.dir/build
.PHONY : Game-Server/fast

#=============================================================================
# Target rules for targets named Game-Client

# Build rule for target.
Game-Client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Game-Client
.PHONY : Game-Client

# fast build rule for target.
Game-Client/fast:
	$(MAKE) -f CMakeFiles/Game-Client.dir/build.make CMakeFiles/Game-Client.dir/build
.PHONY : Game-Client/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f libs/glfw/CMakeFiles/uninstall.dir/build.make libs/glfw/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f libs/glfw/src/CMakeFiles/glfw.dir/build.make libs/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named IrrXML

# Build rule for target.
IrrXML: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IrrXML
.PHONY : IrrXML

# fast build rule for target.
IrrXML/fast:
	$(MAKE) -f libs/assimp/contrib/irrXML/CMakeFiles/IrrXML.dir/build.make libs/assimp/contrib/irrXML/CMakeFiles/IrrXML.dir/build
.PHONY : IrrXML/fast

#=============================================================================
# Target rules for targets named assimp

# Build rule for target.
assimp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 assimp
.PHONY : assimp

# fast build rule for target.
assimp/fast:
	$(MAKE) -f libs/assimp/code/CMakeFiles/assimp.dir/build.make libs/assimp/code/CMakeFiles/assimp.dir/build
.PHONY : assimp/fast

libs/glad/src/glad.o: libs/glad/src/glad.c.o

.PHONY : libs/glad/src/glad.o

# target to build an object file
libs/glad/src/glad.c.o:
	$(MAKE) -f CMakeFiles/Game-Client.dir/build.make CMakeFiles/Game-Client.dir/libs/glad/src/glad.c.o
.PHONY : libs/glad/src/glad.c.o

libs/glad/src/glad.i: libs/glad/src/glad.c.i

.PHONY : libs/glad/src/glad.i

# target to preprocess a source file
libs/glad/src/glad.c.i:
	$(MAKE) -f CMakeFiles/Game-Client.dir/build.make CMakeFiles/Game-Client.dir/libs/glad/src/glad.c.i
.PHONY : libs/glad/src/glad.c.i

libs/glad/src/glad.s: libs/glad/src/glad.c.s

.PHONY : libs/glad/src/glad.s

# target to generate assembly for a file
libs/glad/src/glad.c.s:
	$(MAKE) -f CMakeFiles/Game-Client.dir/build.make CMakeFiles/Game-Client.dir/libs/glad/src/glad.c.s
.PHONY : libs/glad/src/glad.c.s

src/graphics/src/mesh.o: src/graphics/src/mesh.cpp.o

.PHONY : src/graphics/src/mesh.o

# target to build an object file
src/graphics/src/mesh.cpp.o:
	$(MAKE) -f CMakeFiles/Game-Client.dir/build.make CMakeFiles/Game-Client.dir/src/graphics/src/mesh.cpp.o
.PHONY : src/graphics/src/mesh.cpp.o

src/graphics/src/mesh.i: src/graphics/src/mesh.cpp.i

.PHONY : src/graphics/src/mesh.i

# target to preprocess a source file
src/graphics/src/mesh.cpp.i:
	$(MAKE) -f CMakeFiles/Game-Client.dir/build.make CMakeFiles/Game-Client.dir/src/graphics/src/mesh.cpp.i
.PHONY : src/graphics/src/mesh.cpp.i

src/graphics/src/mesh.s: src/graphics/src/mesh.cpp.s

.PHONY : src/graphics/src/mesh.s

# target to generate assembly for a file
src/graphics/src/mesh.cpp.s:
	$(MAKE) -f CMakeFiles/Game-Client.dir/build.make CMakeFiles/Game-Client.dir/src/graphics/src/mesh.cpp.s
.PHONY : src/graphics/src/mesh.cpp.s

src/graphics/src/model.o: src/graphics/src/model.cpp.o

.PHONY : src/graphics/src/model.o

# target to build an object file
src/graphics/src/model.cpp.o:
	$(MAKE) -f CMakeFiles/Game-Client.dir/build.make CMakeFiles/Game-Client.dir/src/graphics/src/model.cpp.o
.PHONY : src/graphics/src/model.cpp.o

src/graphics/src/model.i: src/graphics/src/model.cpp.i

.PHONY : src/graphics/src/model.i

# target to preprocess a source file
src/graphics/src/model.cpp.i:
	$(MAKE) -f CMakeFiles/Game-Client.dir/build.make CMakeFiles/Game-Client.dir/src/graphics/src/model.cpp.i
.PHONY : src/graphics/src/model.cpp.i

src/graphics/src/model.s: src/graphics/src/model.cpp.s

.PHONY : src/graphics/src/model.s

# target to generate assembly for a file
src/graphics/src/model.cpp.s:
	$(MAKE) -f CMakeFiles/Game-Client.dir/build.make CMakeFiles/Game-Client.dir/src/graphics/src/model.cpp.s
.PHONY : src/graphics/src/model.cpp.s

src/graphics/src/shader_loader.o: src/graphics/src/shader_loader.cpp.o

.PHONY : src/graphics/src/shader_loader.o

# target to build an object file
src/graphics/src/shader_loader.cpp.o:
	$(MAKE) -f CMakeFiles/Game-Client.dir/build.make CMakeFiles/Game-Client.dir/src/graphics/src/shader_loader.cpp.o
.PHONY : src/graphics/src/shader_loader.cpp.o

src/graphics/src/shader_loader.i: src/graphics/src/shader_loader.cpp.i

.PHONY : src/graphics/src/shader_loader.i

# target to preprocess a source file
src/graphics/src/shader_loader.cpp.i:
	$(MAKE) -f CMakeFiles/Game-Client.dir/build.make CMakeFiles/Game-Client.dir/src/graphics/src/shader_loader.cpp.i
.PHONY : src/graphics/src/shader_loader.cpp.i

src/graphics/src/shader_loader.s: src/graphics/src/shader_loader.cpp.s

.PHONY : src/graphics/src/shader_loader.s

# target to generate assembly for a file
src/graphics/src/shader_loader.cpp.s:
	$(MAKE) -f CMakeFiles/Game-Client.dir/build.make CMakeFiles/Game-Client.dir/src/graphics/src/shader_loader.cpp.s
.PHONY : src/graphics/src/shader_loader.cpp.s

src/main_loops/src/client_loop.o: src/main_loops/src/client_loop.cpp.o

.PHONY : src/main_loops/src/client_loop.o

# target to build an object file
src/main_loops/src/client_loop.cpp.o:
	$(MAKE) -f CMakeFiles/Game-Client.dir/build.make CMakeFiles/Game-Client.dir/src/main_loops/src/client_loop.cpp.o
.PHONY : src/main_loops/src/client_loop.cpp.o

src/main_loops/src/client_loop.i: src/main_loops/src/client_loop.cpp.i

.PHONY : src/main_loops/src/client_loop.i

# target to preprocess a source file
src/main_loops/src/client_loop.cpp.i:
	$(MAKE) -f CMakeFiles/Game-Client.dir/build.make CMakeFiles/Game-Client.dir/src/main_loops/src/client_loop.cpp.i
.PHONY : src/main_loops/src/client_loop.cpp.i

src/main_loops/src/client_loop.s: src/main_loops/src/client_loop.cpp.s

.PHONY : src/main_loops/src/client_loop.s

# target to generate assembly for a file
src/main_loops/src/client_loop.cpp.s:
	$(MAKE) -f CMakeFiles/Game-Client.dir/build.make CMakeFiles/Game-Client.dir/src/main_loops/src/client_loop.cpp.s
.PHONY : src/main_loops/src/client_loop.cpp.s

src/main_loops/src/server_loop.o: src/main_loops/src/server_loop.cpp.o

.PHONY : src/main_loops/src/server_loop.o

# target to build an object file
src/main_loops/src/server_loop.cpp.o:
	$(MAKE) -f CMakeFiles/Game-Server.dir/build.make CMakeFiles/Game-Server.dir/src/main_loops/src/server_loop.cpp.o
.PHONY : src/main_loops/src/server_loop.cpp.o

src/main_loops/src/server_loop.i: src/main_loops/src/server_loop.cpp.i

.PHONY : src/main_loops/src/server_loop.i

# target to preprocess a source file
src/main_loops/src/server_loop.cpp.i:
	$(MAKE) -f CMakeFiles/Game-Server.dir/build.make CMakeFiles/Game-Server.dir/src/main_loops/src/server_loop.cpp.i
.PHONY : src/main_loops/src/server_loop.cpp.i

src/main_loops/src/server_loop.s: src/main_loops/src/server_loop.cpp.s

.PHONY : src/main_loops/src/server_loop.s

# target to generate assembly for a file
src/main_loops/src/server_loop.cpp.s:
	$(MAKE) -f CMakeFiles/Game-Server.dir/build.make CMakeFiles/Game-Server.dir/src/main_loops/src/server_loop.cpp.s
.PHONY : src/main_loops/src/server_loop.cpp.s

src/network/server/src/server.o: src/network/server/src/server.cpp.o

.PHONY : src/network/server/src/server.o

# target to build an object file
src/network/server/src/server.cpp.o:
	$(MAKE) -f CMakeFiles/Game-Server.dir/build.make CMakeFiles/Game-Server.dir/src/network/server/src/server.cpp.o
.PHONY : src/network/server/src/server.cpp.o

src/network/server/src/server.i: src/network/server/src/server.cpp.i

.PHONY : src/network/server/src/server.i

# target to preprocess a source file
src/network/server/src/server.cpp.i:
	$(MAKE) -f CMakeFiles/Game-Server.dir/build.make CMakeFiles/Game-Server.dir/src/network/server/src/server.cpp.i
.PHONY : src/network/server/src/server.cpp.i

src/network/server/src/server.s: src/network/server/src/server.cpp.s

.PHONY : src/network/server/src/server.s

# target to generate assembly for a file
src/network/server/src/server.cpp.s:
	$(MAKE) -f CMakeFiles/Game-Server.dir/build.make CMakeFiles/Game-Server.dir/src/network/server/src/server.cpp.s
.PHONY : src/network/server/src/server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... install"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Game-Server"
	@echo "... list_install_components"
	@echo "... Game-Client"
	@echo "... uninstall"
	@echo "... glfw"
	@echo "... IrrXML"
	@echo "... assimp"
	@echo "... libs/glad/src/glad.o"
	@echo "... libs/glad/src/glad.i"
	@echo "... libs/glad/src/glad.s"
	@echo "... src/graphics/src/mesh.o"
	@echo "... src/graphics/src/mesh.i"
	@echo "... src/graphics/src/mesh.s"
	@echo "... src/graphics/src/model.o"
	@echo "... src/graphics/src/model.i"
	@echo "... src/graphics/src/model.s"
	@echo "... src/graphics/src/shader_loader.o"
	@echo "... src/graphics/src/shader_loader.i"
	@echo "... src/graphics/src/shader_loader.s"
	@echo "... src/main_loops/src/client_loop.o"
	@echo "... src/main_loops/src/client_loop.i"
	@echo "... src/main_loops/src/client_loop.s"
	@echo "... src/main_loops/src/server_loop.o"
	@echo "... src/main_loops/src/server_loop.i"
	@echo "... src/main_loops/src/server_loop.s"
	@echo "... src/network/server/src/server.o"
	@echo "... src/network/server/src/server.i"
	@echo "... src/network/server/src/server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

