// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: actionHandler.proto

#include "actionHandler.pb.h"
#include "actionHandler.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* inputHandler_method_names[] = {
  "/inputHandler/getInput",
};

std::unique_ptr< inputHandler::Stub> inputHandler::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< inputHandler::Stub> stub(new inputHandler::Stub(channel));
  return stub;
}

inputHandler::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_getInput_(inputHandler_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status inputHandler::Stub::getInput(::grpc::ClientContext* context, const ::Input& request, ::Frame* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_getInput_, context, request, response);
}

void inputHandler::Stub::experimental_async::getInput(::grpc::ClientContext* context, const ::Input* request, ::Frame* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_getInput_, context, request, response, std::move(f));
}

void inputHandler::Stub::experimental_async::getInput(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Frame* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_getInput_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::Frame>* inputHandler::Stub::AsyncgetInputRaw(::grpc::ClientContext* context, const ::Input& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::Frame>::Create(channel_.get(), cq, rpcmethod_getInput_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::Frame>* inputHandler::Stub::PrepareAsyncgetInputRaw(::grpc::ClientContext* context, const ::Input& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::Frame>::Create(channel_.get(), cq, rpcmethod_getInput_, context, request, false);
}

inputHandler::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      inputHandler_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< inputHandler::Service, ::Input, ::Frame>(
          std::mem_fn(&inputHandler::Service::getInput), this)));
}

inputHandler::Service::~Service() {
}

::grpc::Status inputHandler::Service::getInput(::grpc::ServerContext* context, const ::Input* request, ::Frame* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


