// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: input_handler.proto

#ifndef PROTOBUF_INCLUDED_input_5fhandler_2eproto
#define PROTOBUF_INCLUDED_input_5fhandler_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_input_5fhandler_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_input_5fhandler_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_input_5fhandler_2eproto();
class Input;
class InputDefaultTypeInternal;
extern InputDefaultTypeInternal _Input_default_instance_;
class InputResponse;
class InputResponseDefaultTypeInternal;
extern InputResponseDefaultTypeInternal _InputResponse_default_instance_;
namespace google {
namespace protobuf {
template<> ::Input* Arena::CreateMaybeMessage<::Input>(Arena*);
template<> ::InputResponse* Arena::CreateMaybeMessage<::InputResponse>(Arena*);
}  // namespace protobuf
}  // namespace google

enum Input_InputAction {
  Input_InputAction_KEY_PRESS = 0,
  Input_InputAction_KEY_RELEASE = 1,
  Input_InputAction_Input_InputAction_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::google::protobuf::int32>::min(),
  Input_InputAction_Input_InputAction_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::google::protobuf::int32>::max()
};
bool Input_InputAction_IsValid(int value);
const Input_InputAction Input_InputAction_InputAction_MIN = Input_InputAction_KEY_PRESS;
const Input_InputAction Input_InputAction_InputAction_MAX = Input_InputAction_KEY_RELEASE;
const int Input_InputAction_InputAction_ARRAYSIZE = Input_InputAction_InputAction_MAX + 1;

const ::google::protobuf::EnumDescriptor* Input_InputAction_descriptor();
inline const ::std::string& Input_InputAction_Name(Input_InputAction value) {
  return ::google::protobuf::internal::NameOfEnum(
    Input_InputAction_descriptor(), value);
}
inline bool Input_InputAction_Parse(
    const ::std::string& name, Input_InputAction* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Input_InputAction>(
    Input_InputAction_descriptor(), name, value);
}
// ===================================================================

class Input :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Input) */ {
 public:
  Input();
  virtual ~Input();

  Input(const Input& from);

  inline Input& operator=(const Input& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Input(Input&& from) noexcept
    : Input() {
    *this = ::std::move(from);
  }

  inline Input& operator=(Input&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Input& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Input* internal_default_instance() {
    return reinterpret_cast<const Input*>(
               &_Input_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Input* other);
  friend void swap(Input& a, Input& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Input* New() const final {
    return CreateMaybeMessage<Input>(nullptr);
  }

  Input* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Input>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Input& from);
  void MergeFrom(const Input& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Input* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef Input_InputAction InputAction;
  static const InputAction KEY_PRESS =
    Input_InputAction_KEY_PRESS;
  static const InputAction KEY_RELEASE =
    Input_InputAction_KEY_RELEASE;
  static inline bool InputAction_IsValid(int value) {
    return Input_InputAction_IsValid(value);
  }
  static const InputAction InputAction_MIN =
    Input_InputAction_InputAction_MIN;
  static const InputAction InputAction_MAX =
    Input_InputAction_InputAction_MAX;
  static const int InputAction_ARRAYSIZE =
    Input_InputAction_InputAction_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  InputAction_descriptor() {
    return Input_InputAction_descriptor();
  }
  static inline const ::std::string& InputAction_Name(InputAction value) {
    return Input_InputAction_Name(value);
  }
  static inline bool InputAction_Parse(const ::std::string& name,
      InputAction* value) {
    return Input_InputAction_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // uint32 inputKey = 1;
  void clear_inputkey();
  static const int kInputKeyFieldNumber = 1;
  ::google::protobuf::uint32 inputkey() const;
  void set_inputkey(::google::protobuf::uint32 value);

  // .Input.InputAction action = 2;
  void clear_action();
  static const int kActionFieldNumber = 2;
  ::Input_InputAction action() const;
  void set_action(::Input_InputAction value);

  // @@protoc_insertion_point(class_scope:Input)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 inputkey_;
  int action_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_input_5fhandler_2eproto;
};
// -------------------------------------------------------------------

class InputResponse :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:InputResponse) */ {
 public:
  InputResponse();
  virtual ~InputResponse();

  InputResponse(const InputResponse& from);

  inline InputResponse& operator=(const InputResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  InputResponse(InputResponse&& from) noexcept
    : InputResponse() {
    *this = ::std::move(from);
  }

  inline InputResponse& operator=(InputResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const InputResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const InputResponse* internal_default_instance() {
    return reinterpret_cast<const InputResponse*>(
               &_InputResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(InputResponse* other);
  friend void swap(InputResponse& a, InputResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline InputResponse* New() const final {
    return CreateMaybeMessage<InputResponse>(nullptr);
  }

  InputResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<InputResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const InputResponse& from);
  void MergeFrom(const InputResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InputResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 response = 1;
  void clear_response();
  static const int kResponseFieldNumber = 1;
  ::google::protobuf::uint32 response() const;
  void set_response(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:InputResponse)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 response_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_input_5fhandler_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Input

// uint32 inputKey = 1;
inline void Input::clear_inputkey() {
  inputkey_ = 0u;
}
inline ::google::protobuf::uint32 Input::inputkey() const {
  // @@protoc_insertion_point(field_get:Input.inputKey)
  return inputkey_;
}
inline void Input::set_inputkey(::google::protobuf::uint32 value) {
  
  inputkey_ = value;
  // @@protoc_insertion_point(field_set:Input.inputKey)
}

// .Input.InputAction action = 2;
inline void Input::clear_action() {
  action_ = 0;
}
inline ::Input_InputAction Input::action() const {
  // @@protoc_insertion_point(field_get:Input.action)
  return static_cast< ::Input_InputAction >(action_);
}
inline void Input::set_action(::Input_InputAction value) {
  
  action_ = value;
  // @@protoc_insertion_point(field_set:Input.action)
}

// -------------------------------------------------------------------

// InputResponse

// uint32 response = 1;
inline void InputResponse::clear_response() {
  response_ = 0u;
}
inline ::google::protobuf::uint32 InputResponse::response() const {
  // @@protoc_insertion_point(field_get:InputResponse.response)
  return response_;
}
inline void InputResponse::set_response(::google::protobuf::uint32 value) {
  
  response_ = value;
  // @@protoc_insertion_point(field_set:InputResponse.response)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::Input_InputAction> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Input_InputAction>() {
  return ::Input_InputAction_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_input_5fhandler_2eproto
