// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: input_handler.proto

#include "input_handler.pb.h"
#include "input_handler.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* InputHandler_method_names[] = {
  "/InputHandler/sendInput",
};

std::unique_ptr< InputHandler::Stub> InputHandler::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< InputHandler::Stub> stub(new InputHandler::Stub(channel));
  return stub;
}

InputHandler::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_sendInput_(InputHandler_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status InputHandler::Stub::sendInput(::grpc::ClientContext* context, const ::Input& request, ::InputResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_sendInput_, context, request, response);
}

void InputHandler::Stub::experimental_async::sendInput(::grpc::ClientContext* context, const ::Input* request, ::InputResponse* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_sendInput_, context, request, response, std::move(f));
}

void InputHandler::Stub::experimental_async::sendInput(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::InputResponse* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_sendInput_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::InputResponse>* InputHandler::Stub::AsyncsendInputRaw(::grpc::ClientContext* context, const ::Input& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::InputResponse>::Create(channel_.get(), cq, rpcmethod_sendInput_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::InputResponse>* InputHandler::Stub::PrepareAsyncsendInputRaw(::grpc::ClientContext* context, const ::Input& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::InputResponse>::Create(channel_.get(), cq, rpcmethod_sendInput_, context, request, false);
}

InputHandler::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      InputHandler_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< InputHandler::Service, ::Input, ::InputResponse>(
          std::mem_fn(&InputHandler::Service::sendInput), this)));
}

InputHandler::Service::~Service() {
}

::grpc::Status InputHandler::Service::sendInput(::grpc::ServerContext* context, const ::Input* request, ::InputResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


