// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: object_handler.proto
#ifndef GRPC_object_5fhandler_2eproto__INCLUDED
#define GRPC_object_5fhandler_2eproto__INCLUDED

#include "object_handler.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

class ObjectHandler final {
 public:
  static constexpr char const* service_full_name() {
    return "ObjectHandler";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status initPlayer(::grpc::ClientContext* context, const ::PlayerParams& request, ::PlayerInfo* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::PlayerInfo>> AsyncinitPlayer(::grpc::ClientContext* context, const ::PlayerParams& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::PlayerInfo>>(AsyncinitPlayerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::PlayerInfo>> PrepareAsyncinitPlayer(::grpc::ClientContext* context, const ::PlayerParams& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::PlayerInfo>>(PrepareAsyncinitPlayerRaw(context, request, cq));
    }
    virtual ::grpc::Status getPlayers(::grpc::ClientContext* context, const ::PlayerParams& request, ::Players* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Players>> AsyncgetPlayers(::grpc::ClientContext* context, const ::PlayerParams& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Players>>(AsyncgetPlayersRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Players>> PrepareAsyncgetPlayers(::grpc::ClientContext* context, const ::PlayerParams& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Players>>(PrepareAsyncgetPlayersRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void initPlayer(::grpc::ClientContext* context, const ::PlayerParams* request, ::PlayerInfo* response, std::function<void(::grpc::Status)>) = 0;
      virtual void initPlayer(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::PlayerInfo* response, std::function<void(::grpc::Status)>) = 0;
      virtual void getPlayers(::grpc::ClientContext* context, const ::PlayerParams* request, ::Players* response, std::function<void(::grpc::Status)>) = 0;
      virtual void getPlayers(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Players* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::PlayerInfo>* AsyncinitPlayerRaw(::grpc::ClientContext* context, const ::PlayerParams& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::PlayerInfo>* PrepareAsyncinitPlayerRaw(::grpc::ClientContext* context, const ::PlayerParams& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Players>* AsyncgetPlayersRaw(::grpc::ClientContext* context, const ::PlayerParams& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Players>* PrepareAsyncgetPlayersRaw(::grpc::ClientContext* context, const ::PlayerParams& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status initPlayer(::grpc::ClientContext* context, const ::PlayerParams& request, ::PlayerInfo* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::PlayerInfo>> AsyncinitPlayer(::grpc::ClientContext* context, const ::PlayerParams& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::PlayerInfo>>(AsyncinitPlayerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::PlayerInfo>> PrepareAsyncinitPlayer(::grpc::ClientContext* context, const ::PlayerParams& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::PlayerInfo>>(PrepareAsyncinitPlayerRaw(context, request, cq));
    }
    ::grpc::Status getPlayers(::grpc::ClientContext* context, const ::PlayerParams& request, ::Players* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Players>> AsyncgetPlayers(::grpc::ClientContext* context, const ::PlayerParams& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Players>>(AsyncgetPlayersRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Players>> PrepareAsyncgetPlayers(::grpc::ClientContext* context, const ::PlayerParams& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Players>>(PrepareAsyncgetPlayersRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void initPlayer(::grpc::ClientContext* context, const ::PlayerParams* request, ::PlayerInfo* response, std::function<void(::grpc::Status)>) override;
      void initPlayer(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::PlayerInfo* response, std::function<void(::grpc::Status)>) override;
      void getPlayers(::grpc::ClientContext* context, const ::PlayerParams* request, ::Players* response, std::function<void(::grpc::Status)>) override;
      void getPlayers(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Players* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::PlayerInfo>* AsyncinitPlayerRaw(::grpc::ClientContext* context, const ::PlayerParams& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::PlayerInfo>* PrepareAsyncinitPlayerRaw(::grpc::ClientContext* context, const ::PlayerParams& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Players>* AsyncgetPlayersRaw(::grpc::ClientContext* context, const ::PlayerParams& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Players>* PrepareAsyncgetPlayersRaw(::grpc::ClientContext* context, const ::PlayerParams& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_initPlayer_;
    const ::grpc::internal::RpcMethod rpcmethod_getPlayers_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status initPlayer(::grpc::ServerContext* context, const ::PlayerParams* request, ::PlayerInfo* response);
    virtual ::grpc::Status getPlayers(::grpc::ServerContext* context, const ::PlayerParams* request, ::Players* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_initPlayer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_initPlayer() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_initPlayer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status initPlayer(::grpc::ServerContext* context, const ::PlayerParams* request, ::PlayerInfo* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestinitPlayer(::grpc::ServerContext* context, ::PlayerParams* request, ::grpc::ServerAsyncResponseWriter< ::PlayerInfo>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_getPlayers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_getPlayers() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_getPlayers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getPlayers(::grpc::ServerContext* context, const ::PlayerParams* request, ::Players* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetPlayers(::grpc::ServerContext* context, ::PlayerParams* request, ::grpc::ServerAsyncResponseWriter< ::Players>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_initPlayer<WithAsyncMethod_getPlayers<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_initPlayer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_initPlayer() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::PlayerParams, ::PlayerInfo>(
          [this](::grpc::ServerContext* context,
                 const ::PlayerParams* request,
                 ::PlayerInfo* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->initPlayer(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_initPlayer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status initPlayer(::grpc::ServerContext* context, const ::PlayerParams* request, ::PlayerInfo* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void initPlayer(::grpc::ServerContext* context, const ::PlayerParams* request, ::PlayerInfo* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_getPlayers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_getPlayers() {
      ::grpc::Service::experimental().MarkMethodCallback(1,
        new ::grpc::internal::CallbackUnaryHandler< ::PlayerParams, ::Players>(
          [this](::grpc::ServerContext* context,
                 const ::PlayerParams* request,
                 ::Players* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->getPlayers(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_getPlayers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getPlayers(::grpc::ServerContext* context, const ::PlayerParams* request, ::Players* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void getPlayers(::grpc::ServerContext* context, const ::PlayerParams* request, ::Players* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_initPlayer<ExperimentalWithCallbackMethod_getPlayers<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_initPlayer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_initPlayer() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_initPlayer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status initPlayer(::grpc::ServerContext* context, const ::PlayerParams* request, ::PlayerInfo* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_getPlayers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_getPlayers() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_getPlayers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getPlayers(::grpc::ServerContext* context, const ::PlayerParams* request, ::Players* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_initPlayer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_initPlayer() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_initPlayer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status initPlayer(::grpc::ServerContext* context, const ::PlayerParams* request, ::PlayerInfo* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestinitPlayer(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_getPlayers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_getPlayers() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_getPlayers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getPlayers(::grpc::ServerContext* context, const ::PlayerParams* request, ::Players* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetPlayers(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_initPlayer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_initPlayer() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->initPlayer(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_initPlayer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status initPlayer(::grpc::ServerContext* context, const ::PlayerParams* request, ::PlayerInfo* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void initPlayer(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_getPlayers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_getPlayers() {
      ::grpc::Service::experimental().MarkMethodRawCallback(1,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->getPlayers(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_getPlayers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getPlayers(::grpc::ServerContext* context, const ::PlayerParams* request, ::Players* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void getPlayers(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_initPlayer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_initPlayer() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::PlayerParams, ::PlayerInfo>(std::bind(&WithStreamedUnaryMethod_initPlayer<BaseClass>::StreamedinitPlayer, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_initPlayer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status initPlayer(::grpc::ServerContext* context, const ::PlayerParams* request, ::PlayerInfo* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedinitPlayer(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::PlayerParams,::PlayerInfo>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_getPlayers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_getPlayers() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::PlayerParams, ::Players>(std::bind(&WithStreamedUnaryMethod_getPlayers<BaseClass>::StreamedgetPlayers, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_getPlayers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status getPlayers(::grpc::ServerContext* context, const ::PlayerParams* request, ::Players* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedgetPlayers(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::PlayerParams,::Players>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_initPlayer<WithStreamedUnaryMethod_getPlayers<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_initPlayer<WithStreamedUnaryMethod_getPlayers<Service > > StreamedService;
};


#endif  // GRPC_object_5fhandler_2eproto__INCLUDED
